### ISSUE TITLE
Updates to error handling

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/zamba#73]
We need to update error handling with two items: 

(1) Catch and skip videos that error so that a single problem does not tank the entire job.
(2) Save errors in a machine readable format (file, message, and traceback) so that it is consumable by zamba cloud.

**Comment by davidscolgan** [comment]
@pjbull would it be simple for you to give an example of how I'd be able to detect which videos have errored?  If I had that I could add the error handling.  Is this system such that you could, instead of calling `manager.predict()` on a list of videos, you call predict on each video, or is all of them being in a batch important?

Or are you thinking some sort of pre-calculation check to make sure the videos are valid video files?
